### ISSUE TITLE
Make bottom bar icons and rename from "item" & "first" to what it actually is

### ISSUE THREAD

**Issue by HirdayGupta** [ucladevx/UCLAEats-iOS#32]
@ayush-patel can maybe also weigh in on what the order of options on the bottom bar should be.

**Comment by HirdayGupta** [comment]
@Cyncia how was this issue closed?

**Comment by Cyncia** [comment]
Oh, I closed it because I've added in the words and icons to the tab bar accordingly to the design on Figma. Just waiting on the new icons Nidhi will be designing.

**Comment by HirdayGupta** [comment]
@Cyncia which branch are these changes in? Also, by convention, we do not close issues until the entire cycle of `new branch`->`make required changes`->`pull request`->`reveiw`->`merge` is complete.

**Comment by Cyncia** [comment]
Oh I see, my bad. I was not aware of the ordering, will do so next time! I have not yet made the pull request yet, hoping to do so tonight.

**Comment by HirdayGupta** [comment]
No worries! Be sure to Pull Request from your new branch into development (and not the default master) 😄
